### ISSUE TITLE
Rotation Rz translation from Yao to PastaQ is incorrect

### ISSUE THREAD

**Issue by StefanoBarison** [QuantumBFS/YaoPastaQ.jl#18]
Good morning,

I just wanted to report a simple bug that I have found in YaoPastaQ.jl :

The rotation Rz  is mapped from Yao to PastaQ as 
```
genlist!(plist, blk::RotationGate{1, Float64, ZGate}, locs, controls) = push!(plist, ("Rz", locs[1], (ϕ = blk.theta,)))
```
but in PastaQ.jl  the gate is defined as
```
gate(::GateName"Rz"; ϕ::Number) = [
  exp(im * ϕ / 2)  0
  0          exp(-im * ϕ / 2)
]
```

I think this can easily be solved with

```
genlist!(plist, blk::RotationGate{1, Float64, ZGate}, locs, controls) = push!(plist, ("Rz", locs[1], (ϕ = -1*blk.theta,)))
```
or something similar.
The others single qubit rotations (Rx,Ry) are well defined.

**Comment by Roger-luo** [comment]
Thanks for the issue, however, I believe this needs upstream PastaQ to change the definition instead of on our side. 

The rotation gates are defined as general rotation on given operators in Yao, as pointed out by @VarLad in Yao, rotation gates are defined by

```tex
\mathbf{I} cos(θ / 2) - im sin(θ / 2) * mat(U)
```

instead of a specific case, and for Rz you will find Yao's Rz is the same as qiskit

https://qiskit.org/documentation/stubs/qiskit.circuit.library.RZGate.html

tho, a global phase doesn't matter for single-qubit gates, I believe for the sake of consistency we might want to report to PastaQ about this.

**Comment by StefanoBarison** [comment]
I agree that is more consistent how it is defined in Yao, since every rotation has the same convention.

Regards.

**Comment by Roger-luo** [comment]
I think now PastaQ updated its definition, @VarLad got time to double-check if that fixes this issue? then we could close this

**Comment by VarLad** [comment]
@Roger-luo Looks good to me :)
